### ISSUE TITLE
Limit WiredTiger Cache Size

### ISSUE THREAD

**Issue by kgcarr** [IBM/ibm-mongodb-operator#29]
WiredTiger is the underlying storage engine for mongoDB. To allow mongoDB to run in a smaller footprint, an update is needed to the `mongod.conf` file in `mongoconfigmap.go`

```
storage:
      dbPath: /data/db
      wiredTiger:
        engineConfig:
          cacheSizeGB: 2
```

The resource request/limit for memory for the mongodb container will be set to 2Gi/5Gi respectively https://github.com/IBM/ibm-mongodb-operator/blob/3626b1142a6deb5a41a3fa82ecea9cd9c42955df/pkg/controller/mongodb/statefulset.go#L156

This will prevent mongoDB from consuming too much memory and getting OOMKilled
