### ISSUE TITLE
Decide which parameters should be exposed and update the API and CRD

### ISSUE THREAD

**Issue by horis233** [IBM/ibm-mongodb-operator#48]
Hi @kgcarr 

Currently, we exposed these parameters from CR
```
            bootstrapImage:
            imageRegistry:
            initImage:
            metricsImage:
            mongoDBPass:
            mongoDBUser:
            replicas:
            storageClass:
```

Could you take a look if we need to expose more parameters from CR and let users input and update the  API and CRD?
