### ISSUE TITLE
Add standard labels/annotations for health check

### ISSUE THREAD

**Issue by kgcarr** [IBM/ibm-mongodb-operator#60]
Add 

```
labels:
        app.kubernetes.io/instance: {service-name}
      annotations:
        productID: "068a62892a1e4db39641342e592daa25"
        clusterhealth.ibm.com/dependencies: namespace.dependencyservice1, dependencyservice2
```
to statefulset
