### ISSUE TITLE
Add annotations to operator deployment

### ISSUE THREAD

**Issue by kgcarr** [IBM/ibm-mongodb-operator#69]
```
annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productVersion: "3.3.0"
        productMetric: FREE
```
